# Generated by Django 5.0.2 on 2024-02-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_films', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='movie_title',
        ),
    ]
