# Generated by Django 5.0.2 on 2024-08-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_films', '0002_rename_film_movie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_director',
            new_name='movie_directors',
        ),
    ]
