apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-product-manager
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: test-product-manager
  template:
    metadata:
      labels:
        app: test-product-manager
    spec:
      containers:
      - name: test-product-manager-container
        image: sgc20081/test-product-manager:v1.10
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: test-product-manager-service
spec:
  selector:
    app: test-product-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: test-product-manager-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
#     nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
#     nginx.ingress.kubernetes.io/proxy-buffering: "off"
#     nginx.ingress.kubernetes.io/proxy-protocol: "true"
# spec:
#   rules:
#   - host: product-manager.pp.ua
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: test-product-manager-service
#             port:
#               number: 80